"""company assets and asset assignments

Revision ID: 1a31b25edc14
Revises: 4ae0dce404c6
Create Date: 2026-09-07 19:54:56.962840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a31b25edc14'
down_revision: Union[str, Sequence[str], None] = '4ae0dce404c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_tag', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('laptop', 'phone', 'vehicle', 'furniture', 'other', name='company_asset_category'), nullable=False),
    sa.Column('status', sa.Enum('available', 'assigned', 'maintenance', 'retired', name='company_asset_status'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_value_minor', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'asset_tag', name='uq_company_asset_org_tag')
    )
    op.create_table('asset_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('condition_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['company_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE company_assets ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE company_assets FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY company_assets_tenant_isolation ON company_assets "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )
    op.execute("ALTER TABLE asset_assignments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE asset_assignments FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY asset_assignments_tenant_isolation ON asset_assignments "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_assignments')
    op.drop_table('company_assets')
    # ### end Alembic commands ###

    sa.Enum(name='company_asset_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='company_asset_category').drop(op.get_bind(), checkfirst=False)
