"""fixed assets

Revision ID: 2156fc6509cc
Revises: a606cc3ab34e
Create Date: 2026-09-07 21:56:33.181718

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2156fc6509cc'
down_revision: Union[str, Sequence[str], None] = 'a606cc3ab34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# New chart-of-accounts defaults this phase needs (mirrors
# app.services.chart_accounts.DEFAULT_ACCOUNTS) — backfilled here for every
# org that predates this migration, same as the earlier accounting-suite
# migrations did for their own new defaults. accumulated_depreciation is a
# contra-asset (a natural credit balance despite being typed "asset") —
# there's no separate contra-asset AccountType, and the balance-sheet
# aggregation's debit-minus-credit formula for assets handles this
# correctly on its own: depreciation postings credit it, so its balance
# goes negative and nets against fixed_assets' cost basis without any
# special-casing.
NEW_DEFAULT_ACCOUNTS = (
    ("fixed_assets", "Fixed Assets", "asset"),
    ("accumulated_depreciation", "Accumulated Depreciation", "asset"),
    ("depreciation_expense", "Depreciation Expense", "expense"),
    ("disposal_gain_loss", "Gain/Loss on Disposal", "expense"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_tag', sa.String(length=64), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('salvage_value_minor', sa.BigInteger(), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disposed', name='fixed_asset_status'), nullable=False),
    sa.Column('disposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disposal_proceeds_minor', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'asset_tag', name='uq_fixed_asset_org_tag')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE fixed_assets ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE fixed_assets FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY fixed_assets_tenant_isolation ON fixed_assets "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )

    connection = op.get_bind()
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organisations"))]
    if org_ids:
        chart_account_type = sa.Enum(
            "asset", "liability", "equity", "revenue", "expense",
            name="chart_account_type",
            create_type=False,
        )
        chart_accounts = sa.table(
            "chart_accounts",
            sa.column("id", sa.UUID()),
            sa.column("org_id", sa.UUID()),
            sa.column("code", sa.String()),
            sa.column("name", sa.String()),
            sa.column("type", chart_account_type),
            sa.column("is_system", sa.Boolean()),
        )
        existing = {
            (row.org_id, row.code)
            for row in connection.execute(sa.text("SELECT org_id, code FROM chart_accounts"))
        }
        connection.execute(
            chart_accounts.insert(),
            [
                {
                    "id": str(uuid.uuid4()),
                    "org_id": org_id,
                    "code": code,
                    "name": name,
                    "type": account_type,
                    "is_system": True,
                }
                for org_id in org_ids
                for code, name, account_type in NEW_DEFAULT_ACCOUNTS
                if (org_id, code) not in existing
            ],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_assets')
    # ### end Alembic commands ###
    sa.Enum(name="fixed_asset_status").drop(op.get_bind(), checkfirst=False)
