"""chart of accounts

Revision ID: 307a5785cad6
Revises: c5edbe9c3efd
Create Date: 2026-09-07 20:46:13.064499

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307a5785cad6'
down_revision: Union[str, Sequence[str], None] = 'c5edbe9c3efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mirrors app.services.chart_accounts.DEFAULT_ACCOUNTS — the codes payroll
# and WHT already write into ledger_entries.account. Backfilled here for
# every org that predates this table so General Ledger has names/types to
# join against immediately; app.services.chart_accounts.seed_default_chart_of_accounts
# gives new orgs the same set going forward.
DEFAULT_ACCOUNTS = (
    ("cash", "Cash", "asset"),
    ("employee_loan_receivable", "Employee Loans Receivable", "asset"),
    ("payroll_expense_gross", "Payroll Expense — Gross Pay", "expense"),
    ("payroll_expense_employer_pension", "Payroll Expense — Employer Pension", "expense"),
    ("payroll_expense_nsitf", "Payroll Expense — NSITF", "expense"),
    ("contractor_expense", "Contractor Expense", "expense"),
    ("paye_payable", "PAYE Payable", "liability"),
    ("pension_payable", "Pension Payable", "liability"),
    ("nhf_payable", "NHF Payable", "liability"),
    ("nsitf_payable", "NSITF Payable", "liability"),
    ("wht_payable", "WHT Payable", "liability"),
    ("net_pay_payable", "Net Pay Payable", "liability"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', name='chart_account_type'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_chart_account_org_code')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE chart_accounts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE chart_accounts FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY chart_accounts_tenant_isolation ON chart_accounts "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )

    connection = op.get_bind()
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organisations"))]
    if org_ids:
        chart_account_type = sa.Enum(
            "asset", "liability", "equity", "revenue", "expense",
            name="chart_account_type",
            create_type=False,
        )
        chart_accounts = sa.table(
            "chart_accounts",
            sa.column("id", sa.UUID()),
            sa.column("org_id", sa.UUID()),
            sa.column("code", sa.String()),
            sa.column("name", sa.String()),
            sa.column("type", chart_account_type),
            sa.column("is_system", sa.Boolean()),
        )
        connection.execute(
            chart_accounts.insert(),
            [
                {
                    "id": str(uuid.uuid4()),
                    "org_id": org_id,
                    "code": code,
                    "name": name,
                    "type": account_type,
                    "is_system": True,
                }
                for org_id in org_ids
                for code, name, account_type in DEFAULT_ACCOUNTS
            ],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_accounts')
    # ### end Alembic commands ###
    sa.Enum(name="chart_account_type").drop(op.get_bind(), checkfirst=False)
