"""policies

Revision ID: 42710045a2b5
Revises: 8fe94d85394e
Create Date: 2026-09-07 15:05:34.709880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42710045a2b5'
down_revision: Union[str, Sequence[str], None] = '8fe94d85394e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'title', name='uq_policy_org_title')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE policies ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE policies FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY policies_tenant_isolation ON policies "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
