"""shifts

Revision ID: 43b6201529b3
Revises: 42710045a2b5
Create Date: 2026-09-07 15:36:05.007498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b6201529b3'
down_revision: Union[str, Sequence[str], None] = '42710045a2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_shift_org_name')
    )
    op.add_column('employees', sa.Column('shift_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_employees_shift_id', 'employees', 'shifts', ['shift_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE shifts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE shifts FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY shifts_tenant_isolation ON shifts "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_shift_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'shift_id')
    op.drop_table('shifts')
    # ### end Alembic commands ###
