"""union memberships

Revision ID: 4ae0dce404c6
Revises: 7aad3004952d
Create Date: 2026-09-07 19:25:51.503707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae0dce404c6'
down_revision: Union[str, Sequence[str], None] = '7aad3004952d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('union_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('union_name', sa.String(length=255), nullable=False),
    sa.Column('membership_number', sa.String(length=64), nullable=True),
    sa.Column('monthly_dues_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'terminated', name='union_membership_status'), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('terminated_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE union_memberships ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE union_memberships FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY union_memberships_tenant_isolation ON union_memberships "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('union_memberships')
    # ### end Alembic commands ###

    sa.Enum(name='union_membership_status').drop(op.get_bind(), checkfirst=False)
