"""initial: organisations, accounts, memberships

Revision ID: 732375b6547b
Revises: 
Create Date: 2026-09-06 20:53:11.537222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732375b6547b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rc_number', sa.String(length=64), nullable=True),
    sa.Column('company_tin', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'payroll_manager', 'manager', 'employee', name='membership_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'org_id', name='uq_membership_account_org')
    )
    # ### end Alembic commands ###

    # Tenant isolation via a session-local GUC (SET LOCAL app.current_org),
    # read by this policy. accounts and memberships are identity/directory
    # tables, not tenant business data, so they carry no RLS: a login flow
    # must be able to look up an account and its memberships before any
    # tenant context exists. organisations is the first tenant-scoped table;
    # every future business table (employees, pay runs, ...) gets the same
    # ENABLE + FORCE + policy triplet.
    op.execute("ALTER TABLE organisations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organisations FORCE ROW LEVEL SECURITY")
    # NULLIF(..., '') matters: an unset custom GUC can come back as either
    # NULL or '' depending on connection-pooling history, and casting ''
    # straight to uuid raises rather than just failing the comparison.
    op.execute(
        "CREATE POLICY organisations_tenant_isolation ON organisations "
        "USING (id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS organisations_tenant_isolation ON organisations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
    sa.Enum(name='membership_role').drop(op.get_bind(), checkfirst=False)
