"""disciplinary cases

Revision ID: 77744a40731b
Revises: aee812addc30
Create Date: 2026-09-07 18:45:03.548000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77744a40731b'
down_revision: Union[str, Sequence[str], None] = 'aee812addc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinary_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('misconduct', 'attendance', 'policy_violation', 'harassment', 'other', name='disciplinary_case_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved', 'dismissed', name='disciplinary_case_status'), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('action_taken', sa.Enum('none', 'verbal_warning', 'written_warning', 'suspension', 'termination', name='disciplinary_case_action'), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE disciplinary_cases ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE disciplinary_cases FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY disciplinary_cases_tenant_isolation ON disciplinary_cases "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disciplinary_cases')
    # ### end Alembic commands ###

    sa.Enum(name='disciplinary_case_action').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='disciplinary_case_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='disciplinary_case_category').drop(op.get_bind(), checkfirst=False)
