"""contractor withholding tax (WHT)

Revision ID: 802c9a295881
Revises: eda3a6ca882d
Create Date: 2026-09-07 09:00:42.890282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802c9a295881'
down_revision: Union[str, Sequence[str], None] = 'eda3a6ca882d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tin', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wht_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('gross_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('wht_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('certificate_number', sa.String(length=64), nullable=False),
    sa.Column('rule_version_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    # ### end Alembic commands ###

    # New scheme for the existing liability_scheme enum (statutory_liabilities
    # already exists and uses it) — Postgres has no ADD VALUE ... IF NOT
    # EXISTS-free downgrade path for a single value, so this is forward-only,
    # same as every other enum addition in this codebase's history.
    op.execute("ALTER TYPE liability_scheme ADD VALUE IF NOT EXISTS 'wht'")

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    for table in ("contractors", "wht_payments"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant_isolation ON {table} "
            f"USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
        )

    # wht_payments is the certificate of record — append-only, same trigger
    # function payslips/ledger_entries/loan_repayments already use.
    # contractors stays mutable (bank details, TIN can be corrected).
    op.execute(
        "CREATE TRIGGER trg_wht_payments_append_only "
        "BEFORE UPDATE OR DELETE ON wht_payments "
        "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wht_payments')
    op.drop_table('contractors')
    # ### end Alembic commands ###

    # The 'wht' value added to liability_scheme above is not removed here —
    # Postgres has no DROP VALUE for enums short of recreating the type,
    # and liability_scheme is still in use by statutory_liabilities.
