"""job grades

Revision ID: 8fe94d85394e
Revises: 9abadf886d64
Create Date: 2026-09-07 14:52:05.351299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe94d85394e'
down_revision: Union[str, Sequence[str], None] = '9abadf886d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('min_salary_minor', sa.BigInteger(), nullable=True),
    sa.Column('max_salary_minor', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_job_grade_org_name')
    )
    op.add_column('employees', sa.Column('job_grade_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_employees_job_grade_id', 'employees', 'job_grades', ['job_grade_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE job_grades ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job_grades FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY job_grades_tenant_isolation ON job_grades "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_job_grade_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'job_grade_id')
    op.drop_table('job_grades')
    # ### end Alembic commands ###
