"""vendors and bills

Revision ID: 94fe2eddc7f2
Revises: 307a5785cad6
Create Date: 2026-09-07 21:17:48.974991

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fe2eddc7f2'
down_revision: Union[str, Sequence[str], None] = '307a5785cad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# New chart-of-accounts defaults this phase needs (mirrors
# app.services.chart_accounts.DEFAULT_ACCOUNTS) — backfilled here for every
# org that predates this migration, same as the original chart-of-accounts
# migration did for its own defaults.
NEW_DEFAULT_ACCOUNTS = (
    ("accounts_payable", "Accounts Payable", "liability"),
    ("accounts_receivable", "Accounts Receivable", "asset"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('tin', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_vendor_org_name')
    )
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=64), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('expense_account_code', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'paid', 'void', name='bill_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'bill_number', name='uq_bill_org_number')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    for table in ("vendors", "bills"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant_isolation ON {table} "
            "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
        )

    connection = op.get_bind()
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organisations"))]
    if org_ids:
        chart_account_type = sa.Enum(
            "asset", "liability", "equity", "revenue", "expense",
            name="chart_account_type",
            create_type=False,
        )
        chart_accounts = sa.table(
            "chart_accounts",
            sa.column("id", sa.UUID()),
            sa.column("org_id", sa.UUID()),
            sa.column("code", sa.String()),
            sa.column("name", sa.String()),
            sa.column("type", chart_account_type),
            sa.column("is_system", sa.Boolean()),
        )
        existing = {
            (row.org_id, row.code)
            for row in connection.execute(sa.text("SELECT org_id, code FROM chart_accounts"))
        }
        connection.execute(
            chart_accounts.insert(),
            [
                {
                    "id": str(uuid.uuid4()),
                    "org_id": org_id,
                    "code": code,
                    "name": name,
                    "type": account_type,
                    "is_system": True,
                }
                for org_id in org_ids
                for code, name, account_type in NEW_DEFAULT_ACCOUNTS
                if (org_id, code) not in existing
            ],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    op.drop_table('vendors')
    # ### end Alembic commands ###
    sa.Enum(name="bill_status").drop(op.get_bind(), checkfirst=False)
