"""payroll core: employees, bank accounts, pay runs, payslips, ledger entries

Revision ID: a9e0853f4b4b
Revises: 732375b6547b
Create Date: 2026-09-07 03:42:58.108693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e0853f4b4b'
down_revision: Union[str, Sequence[str], None] = '732375b6547b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('marital_status', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('residential_address', sa.String(length=500), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=255), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=32), nullable=True),
    sa.Column('tin', sa.String(length=64), nullable=True),
    sa.Column('pfa_name', sa.String(length=255), nullable=True),
    sa.Column('rsa_pin', sa.String(length=64), nullable=True),
    sa.Column('nhf_number', sa.String(length=64), nullable=True),
    sa.Column('state_of_residence', sa.String(length=64), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('employment_type', sa.Enum('permanent', 'fixed_term', 'part_time', 'intern', 'consultant', name='employment_type'), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('active', 'suspended', 'terminated', name='employee_lifecycle_state'), nullable=False),
    sa.Column('basic_minor', sa.BigInteger(), nullable=False),
    sa.Column('housing_minor', sa.BigInteger(), nullable=False),
    sa.Column('transport_minor', sa.BigInteger(), nullable=False),
    sa.Column('other_earnings_minor', sa.BigInteger(), nullable=False),
    sa.Column('annual_rent_paid_minor', sa.BigInteger(), nullable=False),
    sa.Column('pay_frequency', sa.Enum('monthly', 'weekly', 'biweekly', name='employee_pay_frequency'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'employee_number', name='uq_employee_org_number')
    )
    op.create_table('pay_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('frequency', sa.Enum('monthly', 'weekly', 'biweekly', name='pay_run_frequency'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'completed', 'failed', name='pay_run_status'), nullable=False),
    sa.Column('rule_version_id', sa.String(length=32), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('pay_run_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('debit_minor', sa.BigInteger(), nullable=False),
    sa.Column('credit_minor', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(debit_minor > 0 AND credit_minor = 0) OR (credit_minor > 0 AND debit_minor = 0)', name='ck_ledger_entry_single_sided'),
    sa.CheckConstraint('debit_minor >= 0 AND credit_minor >= 0', name='ck_ledger_entry_nonnegative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_run_id'], ['pay_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('pay_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('pensionable_pay_minor', sa.BigInteger(), nullable=False),
    sa.Column('pension_employee_minor', sa.BigInteger(), nullable=False),
    sa.Column('pension_employer_minor', sa.BigInteger(), nullable=False),
    sa.Column('nhf_minor', sa.BigInteger(), nullable=False),
    sa.Column('paye_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_minor', sa.BigInteger(), nullable=False),
    sa.Column('cumulative_chargeable_income_minor', sa.BigInteger(), nullable=False),
    sa.Column('rule_version_id', sa.String(length=32), nullable=False),
    sa.Column('derivation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_run_id'], ['pay_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation for every business table this phase adds, same
    # pattern as organisations: ENABLE + FORCE + a policy reading the
    # session GUC. bank_accounts, pay_runs, payslips and ledger_entries are
    # all genuinely per-tenant business data, unlike accounts/memberships.
    for table, id_column in (
        ("employees", "org_id"),
        ("bank_accounts", "org_id"),
        ("pay_runs", "org_id"),
        ("payslips", "org_id"),
        ("ledger_entries", "org_id"),
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant_isolation ON {table} "
            f"USING ({id_column} = NULLIF(current_setting('app.current_org', true), '')::uuid)"
        )

    # Append-only enforcement: payslips and ledger entries are corrected by
    # new rows, never edited or deleted in place (python-engineering.md §4).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION forbid_update_delete() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only; % is not allowed', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER trg_payslips_append_only "
        "BEFORE UPDATE OR DELETE ON payslips "
        "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
    )
    op.execute(
        "CREATE TRIGGER trg_ledger_entries_append_only "
        "BEFORE UPDATE OR DELETE ON ledger_entries "
        "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
    )

    # Double-entry invariant: every journal_entry_id's debits must equal its
    # credits. Deferred to transaction commit so a multi-row posting set can
    # be inserted row by row and only needs to balance once fully written.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION check_ledger_entry_balance() RETURNS trigger AS $$
        DECLARE
            imbalance bigint;
        BEGIN
            SELECT COALESCE(SUM(debit_minor) - SUM(credit_minor), 0)
            INTO imbalance
            FROM ledger_entries
            WHERE journal_entry_id = NEW.journal_entry_id;

            IF imbalance <> 0 THEN
                RAISE EXCEPTION
                    'ledger journal_entry_id % is not balanced (debits - credits = %)',
                    NEW.journal_entry_id, imbalance;
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_ledger_entry_balance "
        "AFTER INSERT ON ledger_entries "
        "DEFERRABLE INITIALLY DEFERRED "
        "FOR EACH ROW EXECUTE FUNCTION check_ledger_entry_balance()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS check_ledger_entry_balance() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS forbid_update_delete() CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslips')
    op.drop_table('ledger_entries')
    op.drop_table('bank_accounts')
    op.drop_table('pay_runs')
    op.drop_table('employees')
    # ### end Alembic commands ###

    sa.Enum(name='pay_run_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='pay_run_frequency').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='employee_pay_frequency').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='employee_lifecycle_state').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='employment_type').drop(op.get_bind(), checkfirst=False)
