"""training courses and enrollments

Revision ID: aee812addc30
Revises: dfa8c45a94c0
Create Date: 2026-09-07 18:13:47.646289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee812addc30'
down_revision: Union[str, Sequence[str], None] = 'dfa8c45a94c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'title', name='uq_training_course_org_title')
    )
    op.create_table('training_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('enrolled', 'in_progress', 'completed', 'failed', name='training_enrollment_status'), nullable=False),
    sa.Column('enrolled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE training_courses ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE training_courses FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY training_courses_tenant_isolation ON training_courses "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )
    op.execute("ALTER TABLE training_enrollments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE training_enrollments FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY training_enrollments_tenant_isolation ON training_enrollments "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_enrollments')
    op.drop_table('training_courses')
    # ### end Alembic commands ###

    sa.Enum(name='training_enrollment_status').drop(op.get_bind(), checkfirst=False)
