"""performance reviews

Revision ID: dfa8c45a94c0
Revises: 1fae3e2cd42f
Create Date: 2026-09-07 17:27:04.657885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa8c45a94c0'
down_revision: Union[str, Sequence[str], None] = '1fae3e2cd42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'acknowledged', name='performance_review_status'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('employee_comments', sa.Text(), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('acknowledged_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    op.execute("ALTER TABLE performance_reviews ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE performance_reviews FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY performance_reviews_tenant_isolation ON performance_reviews "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_reviews')
    # ### end Alembic commands ###

    sa.Enum(name='performance_review_status').drop(op.get_bind(), checkfirst=False)
