"""statutory liability tracking

Revision ID: e6ceabd611b4
Revises: f62727df8424
Create Date: 2026-09-07 04:24:44.524823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ceabd611b4'
down_revision: Union[str, Sequence[str], None] = 'f62727df8424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statutory_liabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('pay_run_id', sa.UUID(), nullable=True),
    sa.Column('scheme', sa.Enum('paye', 'pension', 'nhf', 'nsitf', 'itf', name='liability_scheme'), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('authority', sa.String(length=64), nullable=False),
    sa.Column('base_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'filed', 'remitted', name='liability_status'), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remittance_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_run_id'], ['pay_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table. Not append-only: status/filed_at/remitted_at mutate
    # as a liability moves through filing and remittance.
    op.execute("ALTER TABLE statutory_liabilities ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE statutory_liabilities FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY statutory_liabilities_tenant_isolation ON statutory_liabilities "
        "USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statutory_liabilities')
    # ### end Alembic commands ###

    sa.Enum(name='liability_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='liability_scheme').drop(op.get_bind(), checkfirst=False)
