"""self-service: employees.account_id, expenses, benefits

Revision ID: eda3a6ca882d
Revises: e6ceabd611b4
Create Date: 2026-09-07 07:45:44.797754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda3a6ca882d'
down_revision: Union[str, Sequence[str], None] = 'e6ceabd611b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('value_minor', sa.BigInteger(), nullable=True),
    sa.Column('frequency', sa.Enum('one_time', 'monthly', 'annual', name='benefit_frequency'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'reimbursed', name='expense_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reimbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_employees_account_id', 'employees', ['account_id'])
    op.create_foreign_key(
        'fk_employees_account_id_accounts', 'employees', 'accounts', ['account_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table. Not append-only: both expenses and benefits mutate
    # (status transitions, end-dating a benefit), same as leave_requests/
    # loans/statutory_liabilities.
    for table in ("benefits", "expenses"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant_isolation ON {table} "
            f"USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_account_id_accounts', 'employees', type_='foreignkey')
    op.drop_constraint('uq_employees_account_id', 'employees', type_='unique')
    op.drop_column('employees', 'account_id')
    op.drop_table('expenses')
    op.drop_table('benefits')
    # ### end Alembic commands ###

    sa.Enum(name='expense_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='benefit_frequency').drop(op.get_bind(), checkfirst=False)
