"""people ops: loans, leave requests, final settlement

Revision ID: f62727df8424
Revises: a9e0853f4b4b
Create Date: 2026-09-07 03:59:06.223106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62727df8424'
down_revision: Union[str, Sequence[str], None] = 'a9e0853f4b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('annual', 'sick', 'maternity', 'paternity', 'unpaid', name='leave_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('principal_minor', sa.BigInteger(), nullable=False),
    sa.Column('num_installments', sa.Integer(), nullable=False),
    sa.Column('installment_minor', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paid_off', 'cancelled', name='loan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('payslip_id', sa.UUID(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=False),
    sa.Column('leave_days_paid_out', sa.Integer(), nullable=False),
    sa.Column('leave_payout_minor', sa.BigInteger(), nullable=False),
    sa.Column('gratuity_minor', sa.BigInteger(), nullable=False),
    sa.Column('outstanding_loan_recovered_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_settlement_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_repayments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('payslip_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default matches the ORM's Python-side default (20) so this
    # backfills existing rows safely instead of failing on a non-empty table.
    op.add_column(
        'employees',
        sa.Column('annual_leave_entitlement_days', sa.Integer(), nullable=False, server_default='20'),
    )
    # ### end Alembic commands ###

    # Tenant isolation, same ENABLE + FORCE + policy pattern as every other
    # business table.
    for table in ("leave_requests", "loans", "final_settlements", "loan_repayments"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant_isolation ON {table} "
            f"USING (org_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
        )

    # loan_repayments and final_settlements are append-only, same trigger
    # function payslips/ledger_entries already use.
    op.execute(
        "CREATE TRIGGER trg_loan_repayments_append_only "
        "BEFORE UPDATE OR DELETE ON loan_repayments "
        "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
    )
    op.execute(
        "CREATE TRIGGER trg_final_settlements_append_only "
        "BEFORE UPDATE OR DELETE ON final_settlements "
        "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'annual_leave_entitlement_days')
    op.drop_table('loan_repayments')
    op.drop_table('final_settlements')
    op.drop_table('loans')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###

    sa.Enum(name='loan_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='leave_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='leave_type').drop(op.get_bind(), checkfirst=False)
